# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dG1_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, iter_max, stop_tol) {
    .Call(`_EPPS_dG1_normal_rcpp`, X, Y, n1, alpha, beta, sigma, iter_max, stop_tol)
}

lpL_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, iter_max, stop_tol) {
    .Call(`_EPPS_lpL_normal_rcpp`, X, Y, n1, alpha, beta, sigma, iter_max, stop_tol)
}

dG1alt_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol) {
    .Call(`_EPPS_dG1alt_normal_rcpp`, X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol)
}

lpLalt_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol) {
    .Call(`_EPPS_lpLalt_normal_rcpp`, X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol)
}

dG1_logistic_rcpp <- function(X, Y, n1, alpha, beta, iter_max, stop_tol) {
    .Call(`_EPPS_dG1_logistic_rcpp`, X, Y, n1, alpha, beta, iter_max, stop_tol)
}

lpL_logistic_rcpp <- function(X, Y, n1, alpha, beta, iter_max, stop_tol) {
    .Call(`_EPPS_lpL_logistic_rcpp`, X, Y, n1, alpha, beta, iter_max, stop_tol)
}

dG1alt_logistic_rcpp <- function(X, Y, n1, alpha, beta, gamma, iter_max, stop_tol) {
    .Call(`_EPPS_dG1alt_logistic_rcpp`, X, Y, n1, alpha, beta, gamma, iter_max, stop_tol)
}

lpLalt_logistic_rcpp <- function(X, Y, n1, alpha, beta, gamma, iter_max, stop_tol) {
    .Call(`_EPPS_lpLalt_logistic_rcpp`, X, Y, n1, alpha, beta, gamma, iter_max, stop_tol)
}

eXsq_rcpp <- function(data_X) {
    .Call(`_EPPS_eXsq_rcpp`, data_X)
}

eXsq_w_rcpp <- function(data_X, weight) {
    .Call(`_EPPS_eXsq_w_rcpp`, data_X, weight)
}

Xsq_lowtri_rcpp <- function(data_X) {
    .Call(`_EPPS_Xsq_lowtri_rcpp`, data_X)
}

twoXYsym_lowtri_rcpp <- function(data_X, data_Y) {
    .Call(`_EPPS_twoXYsym_lowtri_rcpp`, data_X, data_Y)
}

ctingP_rcpp <- function(Y, y) {
    .Call(`_EPPS_ctingP_rcpp`, Y, y)
}

ctingP_uni_rcpp <- function(Y, y) {
    .Call(`_EPPS_ctingP_uni_rcpp`, Y, y)
}

pinv_rcpp <- function(M_A) {
    .Call(`_EPPS_pinv_rcpp`, M_A)
}

solve_rcpp <- function(M_A, M_B) {
    .Call(`_EPPS_solve_rcpp`, M_A, M_B)
}

inv_sympd_rcpp <- function(M_S) {
    .Call(`_EPPS_inv_sympd_rcpp`, M_S)
}

eigen_rcpp <- function(M_S) {
    .Call(`_EPPS_eigen_rcpp`, M_S)
}

chol_rcpp <- function(M_S) {
    .Call(`_EPPS_chol_rcpp`, M_S)
}

GroupSum_rcpp <- function(MM, id) {
    .Call(`_EPPS_GroupSum_rcpp`, MM, id)
}

countAinB_rcpp <- function(A, B) {
    .Call(`_EPPS_countAinB_rcpp`, A, B)
}

countAinB_W_rcpp <- function(A, B, W) {
    .Call(`_EPPS_countAinB_W_rcpp`, A, B, W)
}

rankAinB_rcpp <- function(A, B) {
    .Call(`_EPPS_rankAinB_rcpp`, A, B)
}

outer_minus_rcpp <- function(a, b) {
    .Call(`_EPPS_outer_minus_rcpp`, a, b)
}

outer_plus_rcpp <- function(a, b) {
    .Call(`_EPPS_outer_plus_rcpp`, a, b)
}

outer_leq_rcpp <- function(a, b) {
    .Call(`_EPPS_outer_leq_rcpp`, a, b)
}

outer_geq_rcpp <- function(a, b) {
    .Call(`_EPPS_outer_geq_rcpp`, a, b)
}

